name: deploy to s3

on:
    push:
        branches:
            - master

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: cypress run
              uses: cypress-io/github-action@v4
            env:
                CYPRESS_apiUrl: ${{secrets.CYPRESS_API_URL}}
                CYPRESS_apiKey: ${{secrets.CYPRESS_API_KEY}}
                CYPRESS_baseUrl: ${{secrets.CYPRESS_BASE_URL}}

    build:
        runs-on: ubuntu-latest
        needs: cypress-run
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v3
            - run: |
                  npm install
                  npm run test
                  npm run build
            - uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl public-read --follow-symlinks --delete
              env:
                  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: "eu-north-1"
                  SOURCE_DIR: "build"
